services:
  shynet:
    container_name: shynet_main
    image: milesmcc/shynet:latest
    restart: unless-stopped
    expose:
      - 8888
    env_file:
      - .env
    environment:
      - DB_HOST=db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8888 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - db
      
  db:
    container_name: shynet_database
    image: postgres
    restart: always
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_DB=${DB_NAME}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./volumes/shynet_db:/var/lib/postgresql/data
      
  webserver:
    container_name: shynet_webserver
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf    
    expose:
      - "80"
    depends_on:
      - shynet
    networks:
      - nginx

volumes:
  shynet_db:

networks:
  nginx:
    external: true
